# Generated by Django 5.2.5 on 2026-04-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
