# Generated by Django 5.2.5 on 2026-04-14 18:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Foi deletado?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('nivel', models.CharField(choices=[('FAC', 'Fácil'), ('MED', 'Médio'), ('DIF', 'Difícil')], max_length=3, verbose_name='Nível')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('objetivo', models.TextField(verbose_name='Objetivo')),
                ('instrucao', models.TextField(verbose_name='Instrução')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Deletado por')),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
                'ordering': ['-created_at'],
            },
        ),
    ]
