# Generated by Django 5.2.5 on 2026-04-07 20:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('is_deleted', models.BooleanField(default=True, verbose_name='Foi deletado?')),
                ('nivel', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('conteudo', models.TextField()),
                ('objetivo', models.TextField()),
                ('instrucao', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
