# Generated by Django 5.2.5 on 2026-04-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercicio',
            options={'ordering': ['-created_at'], 'verbose_name': 'Exercício', 'verbose_name_plural': 'Exercícios'},
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='categoria',
            field=models.CharField(max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='conteudo',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='instrucao',
            field=models.TextField(verbose_name='Instrução'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='nivel',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], max_length=10, verbose_name='Nível'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='objetivo',
            field=models.TextField(verbose_name='Objetivo'),
        ),
    ]
