# Generated by Django 5.2.5 on 2026-04-16 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('instrucao', models.TextField()),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='exercicio.exercicio')),
            ],
        ),
    ]
