# Generated by Django 5.2.5 on 2026-04-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0002_conteudoexercicio'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='paciente',
            field=models.ManyToManyField(blank=True, related_name='exercicios', to='paciente.paciente', verbose_name='Pacientes'),
        ),
    ]
