# Generated by Django 5.2.5 on 2026-04-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0003_exercicio_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
