# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0004_exercicio_concluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Nome'),
        ),
    ]
