# Generated by Django 5.2.5 on 2026-05-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0005_exercicio_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudoexercicio',
            name='audio_referencia',
            field=models.FileField(blank=True, null=True, upload_to='exercicios/referencias/', verbose_name='Áudio de referência'),
        ),
    ]
