# Generated by Django 5.2.5 on 2026-03-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fonoaudiologo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('crfa', models.CharField(max_length=20, unique=True, verbose_name='CRFa')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
            ],
            options={
                'verbose_name': 'Fonoaudiólogo',
                'verbose_name_plural': 'Fonoaudiólogos',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
