# Generated by Django 5.2.5 on 2026-04-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonoaudiologo',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
