# Generated by Django 5.2.5 on 2026-04-07 20:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('is_deleted', models.BooleanField(default=True, verbose_name='Foi deletado?')),
                ('feedback', models.JSONField()),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='exercicio.exercicio')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
