# Generated by Codex on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='audio',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='respostas_audio/',
            ),
        ),
    ]
