# Generated by Django 5.2.5 on 2026-04-25 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonoaudiologo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fonoaudiologo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fonoaudiologo_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário associado'),
        ),
    ]
