# Generated by Django 5.2.5 on 2026-04-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonoaudiologo', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fonoaudiologo',
            field=models.ManyToManyField(blank=True, related_name='pacientes', to='fonoaudiologo.fonoaudiologo', verbose_name='Fonoaudiólogos'),
        ),
    ]
