# Generated by Django 5.2.5 on 2026-04-26 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonoaudiologo', '0002_fonoaudiologo_user'),
        ('paciente', '0003_paciente_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='fonoaudiologo',
        ),
        migrations.AddField(
            model_name='paciente',
            name='fonoaudiologo',
            field=models.ForeignKey(blank=True, default='c8f59f61-14a5-4895-b360-20dd0a3fa3b0', on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='fonoaudiologo.fonoaudiologo', verbose_name='Fonoaudiólogos'),
            preserve_default=False,
        ),
    ]
