# Generated by Django 5.2.5 on 2026-04-28 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_remove_paciente_fonoaudiologo_paciente_fonoaudiologo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='user',
        ),
    ]
